var products = [
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },
    {
        Choices: { ID: 1, Name: "Parent1" },
        models: "737-678",
        planNum: "05-001",
        SIN_Number: "XD-05-810-A",
        eo: "",
        ATA: "0500",
        hresholdValue: "",
        cycleValue: "15000飞行小时",
        zhTitle: "客舱压力渗漏测试。",
        enTitle: "ABIN PRESSURE LEAK TEST.",
        operator: "厦门航空"
    },


]